-- Crear la tabla de calificaciones
CREATE TABLE IF NOT EXISTS public.session_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  session_id BIGINT REFERENCES public.agenda_sessions(id) ON DELETE CASCADE,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
  comment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  CONSTRAINT unique_user_session_rating UNIQUE (user_id, session_id)
);

-- Configurar la privacidad (RLS)
ALTER TABLE public.session_ratings ENABLE ROW LEVEL SECURITY;

-- Los usuarios solo pueden ver las que ellos mismos han creado (para que el botón se apague)
CREATE POLICY "Users can read own ratings." ON public.session_ratings
  FOR SELECT USING (auth.uid() = user_id);

-- Los usuarios solo pueden insertar sus propias calificaciones
CREATE POLICY "Users can insert own ratings." ON public.session_ratings
  FOR INSERT WITH CHECK (auth.uid() = user_id);
  
-- Como eres Admin, puedes crear una política adicinal para ver todo si es necesario,
-- aunque si usas el rol de service_role de supabase todo se saltara el RLS.
